### NumPy

In [1]:
# NumPY.org/doc/stable

In [2]:
# matplotlib lab for drawing, plotting, barchart etc

In [7]:
import numpy as np # if not error no need to install: ! pip install numpy

In [9]:
arr = np.array([1, 3, 4, 5]) # array is same type list, list is different list

In [10]:
arr

array([1, 3, 4, 5])

In [12]:
print(arr)

[1 3 4 5]


In [15]:
arr_2d = np.array([[1, 2, 3], [4, 6, 6]])
print(arr_2d)

[[1 2 3]
 [4 6 6]]


In [22]:
arr_3d = np.array([[[1, 2, 3], [4, 6, 6]],[[6, 9, 6]],[3, 5, 8]]])
print(arr_3d) # pachhi heramla

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (2219262376.py, line 1)

In [23]:
arr_2d.shape #result (2,3)

(2, 3)

In [24]:
arr_2d.size #result (2,3)

6

In [26]:
arr_2d.dtype #result (2,3)

dtype('int64')

In [28]:
# add two array

In [29]:
# slicing and indexing


In [31]:
new_arr = arr[1:4]
print(new_arr)

[3 4 5]


In [34]:
ele = arr_2d[1][1]

In [35]:
print(ele)

6


In [36]:
# array operation

In [37]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 6, 3])
arr1 + arr2

array([5, 8, 6])

In [38]:
arr_sum = arr1 + arr2

In [39]:
print(arr_sum)

[5 8 6]


In [40]:
arr1 = np.array([1, 2, 3,])
arr2 = np.array([4, 6, 3])
arr1 *arr2

array([ 4, 12,  9])

In [41]:
print(arr1 * 5)

[ 5 10 15]


In [42]:
print(arr1 + 5)

[6 7 8]


In [43]:
print(arr1 / 5)

[0.2 0.4 0.6]


In [44]:
# matrix calculation

In [49]:
mat1 = np.array([[2,3],[4,3]])
mat2 = np.array([[6,1],[2,9]])

In [50]:
# addition
mat_add = mat1 + mat2
print(mat_add)

[[ 8  4]
 [ 6 12]]


In [51]:
# Substraction
mat_add = mat1 - mat2
print(mat_add)

[[-4  2]
 [ 2 -6]]


In [52]:
print(mat1 * 3)

[[ 6  9]
 [12  9]]


In [54]:
mat_mul = mat1 @ mat2 # matrix multiplication
print(mat_mul)

[[18 29]
 [30 31]]


In [55]:
print(np.dot(mat1, mat2))

[[18 29]
 [30 31]]


In [56]:
print(mat_mul.T) # transpose

[[18 30]
 [29 31]]


In [59]:
print(np.linalg.inv(mat_mul)) # inverse

[[-0.09935897  0.09294872]
 [ 0.09615385 -0.05769231]]


In [62]:
print(np.linalg.det(mat1))

-6.0


In [63]:
print(np.linalg.eig(mat1)) # Eigen Value

EigResult(eigenvalues=array([-1.,  6.]), eigenvectors=array([[-0.70710678, -0.6       ],
       [ 0.70710678, -0.8       ]]))


In [64]:
#eigen values and eigen vector 

In [65]:
# vector calculation

In [70]:
v1 = np.array([1, 2, 3])
v2 = np.array([3, 4, 5])
print("v1 =", v1)
print("v2 =", v2)


v1 = [1 2 3]
v2 = [3 4 5]


In [72]:
dot_product = np.dot(v1, v2)
print(dot_product)

26


In [71]:
print(v1 @ v2)

26


In [73]:
cross_product = np.dot(v1, v2)
print(cross_product)

26


In [74]:
i j k
1 2 3 
3 4 5 
i (10-12) -5-9) + k (4-6)
-2i+4j-2k
[-2 4 -2] # this is manual calcualtion = abobe cross_propduct

SyntaxError: unmatched ')' (3518377645.py, line 4)

In [75]:
# solve linerar eqequiton Manual calculqtion
# 2x + y = 5
# x + y = 3
# --------------
# x = 2
# y = 1


In [76]:
# A * X = B
# X = (A inv) B


In [81]:
A = np.array([[2, 1], [1, 1]])
B = np.array([5, 3])
X = np.linalg.solve(A, B)
print("Value of (x, y):", x)

Value of (x, y): [2. 1.]


In [82]:
# assingnmet + generat randuom number  fro numpy

In [83]:
np.random.randn(3, 3)

array([[-0.79416751,  0.34060568, -0.15822375],
       [-0.53237126, -0.27814927,  0.21062548],
       [ 0.62454979,  0.96416891, -0.57841148]])