# Working with NumPy

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 3, 4, 5, 6])

In [3]:
arr

array([1, 3, 4, 5, 6])

In [4]:
print(arr)

[1 3 4 5 6]


In [5]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [7]:
arr_3d = np.array([[[1, 2], [3, 4]], [[4, 5], [5, 6]]])

In [8]:
print(arr_3d)

[[[1 2]
  [3 4]]

 [[4 5]
  [5 6]]]


In [9]:
arr_2d.shape

(2, 3)

In [10]:
arr_2d.size

6

In [11]:
arr_3d.shape

(2, 2, 2)

In [12]:
arr_3d.dtype

dtype('int64')

In [14]:
# Slicing and Indexing

new_arr = arr[1:4]
print(new_arr)

ele = arr_2d[1][1]
print(ele)

[3 4 5]
5


## Array operations

In [22]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [23]:
arr_sum = arr1 + arr2
print(arr_sum)

[5 7 9]


In [24]:
arr_mul = arr1 * arr2
print(arr_mul)

[ 4 10 18]


In [26]:
print(arr1 * 5)

[ 5 10 15]


In [27]:
print(arr1 + 5)

[6 7 8]


## Matrix calcultion

In [28]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[2, 3], [4, 5]])

In [31]:
print(f"First Matrix:\n{mat1}")
print(f"Second Matrix:\n{mat2}")

First Matrix:
[[1 2]
 [3 4]]
Second Matrix:
[[2 3]
 [4 5]]


In [33]:
# Addition
mat_add = mat1 + mat2
print(mat_add)

[[3 5]
 [7 9]]


In [34]:
# Subtraction
mat_sub = mat1 - mat2
print(mat_sub)

[[-1 -1]
 [-1 -1]]


In [35]:
print(mat1 * 3)

[[ 3  6]
 [ 9 12]]


In [36]:
mat_mul = mat1 * mat2
print(mat_mul)

[[ 2  6]
 [12 20]]


In [37]:
mat_mul = mat1 @ mat2
print(mat_mul)

[[10 13]
 [22 29]]


In [38]:
print(np.dot(mat1, mat2))

[[10 13]
 [22 29]]


In [39]:
# Transpose
print(mat_mul.T)

[[10 22]
 [13 29]]


In [40]:
print(np.linalg.inv(mat_mul))

[[ 7.25 -3.25]
 [-5.5   2.5 ]]


In [42]:
print(np.linalg.det(mat1))

-2.0000000000000004


In [43]:
print(np.linalg.eig(mat1))

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


## Vector calculation

In [45]:
v1 = np.array([1, 2, 3])
v2 = np.array([3, 4, 5])
print("v1 =", v1)
print("v2 =", v2)

v1 = [1 2 3]
v2 = [3 4 5]


In [47]:
dot_product = np.dot(v1, v2)
print(dot_product)

26


In [49]:
print(v1 @ v2)

26


In [50]:
cross_product = np.cross(v1, v2)
print(cross_product)

[-2  4 -2]


```
i j k
1 2 3
3 4 5

i (10-12) -j (5-9) + k (4-6)
-2i+4j-2k
[-2 4 -2]
```

## solve linear equaltion
```
2x + y = 5
x + y = 3
----------
x = 2
y = 1
```

In [52]:
# A * X = B
# X = (A inv) B

In [56]:
A = np.array([[2, 1], [1, 1]])
B = np.array([5, 3])

X = np.linalg.solve(A, B)
print("Value of (x, y):", X)

Value of (x, y): [2. 1.]


In [57]:
np.random.randn(3, 3)

array([[ 0.44204476,  1.10263907,  2.25603775],
       [-1.00127941,  0.36895738, -0.3890297 ],
       [ 1.10255606,  0.6233641 , -0.54324681]])